---
layout: cv
title: Luis Fernando Mendoza's Resume
---
# Luis Fernando Mendoza
Business Intelligence, Data Analyst

<div id="webaddress">
<a href="datascience@byui.edu">datascience@byui.edu</a>
| <a href="https://byuidatascience.github.io/development.html">Data Science Program</a>
| <a href="https://www.linkedin.com/groups/13537407/">LinkedIn</a>
| <a href="https://github.com/byuids-resumes">GitHub</a>
</div>


## Education

`Expected April 2025`
__Brigham Young University - Idaho__, Rexburg, ID

- Majoring in Business Analytics
- Mainoring in Data Science


## Service and Work History

`May 2018-September 2018`
__Car Wash Associate for Epic Shine__, Meridian, ID

- Worked with a team to give top of the line customer service.
- Preformed janitorial services around the carwash.
- Instructed people in the proper way to use an automated car wash.

`2018-2020`
__Religious Missionary__, Kansas

- Studied rigorously from religious texts daily.
- Taught lessons on religious topics as a team.
- Attended trainings to become better missionaries.

`April 2020-September 2020`
__Warehouse Associate for Scentsy__, Meridian, ID

- Tasked with Moving, packing, shipping, and restocking merchandise.
- Taught to put merchandise together.

`April 2021-November 2021`
__Security Guard for Amazon__, Meridian, ID

- Trained to identify threats to the facility, de-escalate potentially harmful situations, and observe and report suspicious activities to the proper authorities.
- Patrolled the building every hour to regulate the environment and discourage mischief.
- Trained to respond in emergency situations as an escort and administer CPR as needed.

`April 2023-June 2023`
__Gas Station Clerk for Good 2 Go__, Rigby, ID

- Completed purchases for merchandise and/or gas.
- Kept gas station and work area clean and tidy.
- Preformed simple maintenance on machinery.

`July 2023-Present Day`
__Tailored Clothing Specialist for Dillards__, Idaho Falls, ID

- Help customers find what they want and need through asking questions and giving suggestions.
- Teach customers about the benefits of using a Dillards credit card and gude them through the application process.
- Measure customers so they are getting the right fit for them in a variety of shirts, slacks, and suits.

<!-- ### Footer

Last updated: January 2024 -->
